# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_mutualfund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutualfund',
            old_name='plan',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mutualfund',
            old_name='acquired_date',
            new_name='purchase_date',
        ),
        migrations.RenameField(
            model_name='mutualfund',
            old_name='current_value',
            new_name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='mutualfund',
            name='investment_amount',
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='shares',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='symbol',
            field=models.CharField(default=2222, max_length=10),
            preserve_default=False,
        ),
    ]
