# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-15 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20180211_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfund',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutualfunds', to='portfolio.Customer'),
        ),
    ]
