# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-17 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180214_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='current_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mutualfund',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
